-- V1__create_tables.sql
-- Criacao das tabelas do PetCare 360 (CLYVO VET)

CREATE TABLE TB_USUARIO (
    ID_USUARIO UUID NOT NULL,
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD_HASH VARCHAR(100) NOT NULL,
    ROLE VARCHAR(20) NOT NULL,
    CONSTRAINT PK_TB_USUARIO PRIMARY KEY (ID_USUARIO),
    CONSTRAINT UK_TB_USUARIO_USERNAME UNIQUE (USERNAME)
);

CREATE TABLE TB_TUTOR (
    ID_TUTOR UUID NOT NULL,
    NM_TUTOR VARCHAR(100) NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(20),
    ENDERECO VARCHAR(200),
    CONSTRAINT PK_TB_TUTOR PRIMARY KEY (ID_TUTOR),
    CONSTRAINT UK_TB_TUTOR_CPF UNIQUE (CPF),
    CONSTRAINT UK_TB_TUTOR_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE TB_CLINICA (
    ID_CLINICA UUID NOT NULL,
    NM_CLINICA VARCHAR(100) NOT NULL,
    CNPJ VARCHAR(18) NOT NULL,
    EMAIL VARCHAR(100),
    TELEFONE VARCHAR(20),
    ENDERECO VARCHAR(200),
    CONSTRAINT PK_TB_CLINICA PRIMARY KEY (ID_CLINICA),
    CONSTRAINT UK_TB_CLINICA_CNPJ UNIQUE (CNPJ)
);

CREATE TABLE TB_PET (
    ID_PET UUID NOT NULL,
    NM_PET VARCHAR(100) NOT NULL,
    ESPECIE VARCHAR(20) NOT NULL,
    RACA VARCHAR(100),
    DT_NASCIMENTO DATE,
    PESO NUMERIC(5, 2),
    OBSERVACOES VARCHAR(500),
    ID_TUTOR UUID NOT NULL,
    CONSTRAINT PK_TB_PET PRIMARY KEY (ID_PET),
    CONSTRAINT FK_PET_TUTOR FOREIGN KEY (ID_TUTOR) REFERENCES TB_TUTOR(ID_TUTOR)
);

CREATE TABLE TB_CONSULTA (
    ID_CONSULTA UUID NOT NULL,
    DT_CONSULTA TIMESTAMP NOT NULL,
    STATUS_CONSULTA VARCHAR(20) NOT NULL,
    MOTIVO VARCHAR(500),
    DIAGNOSTICO VARCHAR(500),
    VALOR NUMERIC(10, 2),
    ID_PET UUID NOT NULL,
    ID_CLINICA UUID NOT NULL,
    CONSTRAINT PK_TB_CONSULTA PRIMARY KEY (ID_CONSULTA),
    CONSTRAINT FK_CONSULTA_PET FOREIGN KEY (ID_PET) REFERENCES TB_PET(ID_PET),
    CONSTRAINT FK_CONSULTA_CLINICA FOREIGN KEY (ID_CLINICA) REFERENCES TB_CLINICA(ID_CLINICA)
);

CREATE TABLE TB_VACINA (
    ID_VACINA UUID NOT NULL,
    NM_VACINA VARCHAR(100) NOT NULL,
    DT_APLICACAO DATE NOT NULL,
    DT_PROXIMA DATE,
    LOTE VARCHAR(50),
    ID_PET UUID NOT NULL,
    ID_CONSULTA UUID,
    CONSTRAINT PK_TB_VACINA PRIMARY KEY (ID_VACINA),
    CONSTRAINT FK_VACINA_PET FOREIGN KEY (ID_PET) REFERENCES TB_PET(ID_PET),
    CONSTRAINT FK_VACINA_CONSULTA FOREIGN KEY (ID_CONSULTA) REFERENCES TB_CONSULTA(ID_CONSULTA)
);

CREATE TABLE TB_MEDICAMENTO (
    ID_MEDICAMENTO UUID NOT NULL,
    NM_MEDICAMENTO VARCHAR(150) NOT NULL,
    DOSAGEM VARCHAR(100),
    FREQUENCIA VARCHAR(100),
    DT_INICIO DATE NOT NULL,
    DT_FIM DATE,
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    CUSTO NUMERIC(10, 2),
    ID_PET UUID NOT NULL,
    ID_CONSULTA UUID,
    CONSTRAINT PK_TB_MEDICAMENTO PRIMARY KEY (ID_MEDICAMENTO),
    CONSTRAINT FK_MEDICAMENTO_PET FOREIGN KEY (ID_PET) REFERENCES TB_PET(ID_PET),
    CONSTRAINT FK_MEDICAMENTO_CONSULTA FOREIGN KEY (ID_CONSULTA) REFERENCES TB_CONSULTA(ID_CONSULTA)
);

CREATE TABLE TB_AGENDAMENTO (
    ID_AGENDAMENTO UUID NOT NULL,
    DT_AGENDAMENTO TIMESTAMP NOT NULL,
    TIPO VARCHAR(30) NOT NULL,
    STATUS_AGENDAMENTO VARCHAR(20) NOT NULL,
    OBSERVACOES VARCHAR(500),
    ID_PET UUID NOT NULL,
    ID_CLINICA UUID NOT NULL,
    CONSTRAINT PK_TB_AGENDAMENTO PRIMARY KEY (ID_AGENDAMENTO),
    CONSTRAINT FK_AGENDAMENTO_PET FOREIGN KEY (ID_PET) REFERENCES TB_PET(ID_PET),
    CONSTRAINT FK_AGENDAMENTO_CLINICA FOREIGN KEY (ID_CLINICA) REFERENCES TB_CLINICA(ID_CLINICA)
);

CREATE TABLE TB_ALERTA (
    ID_ALERTA UUID NOT NULL,
    TIPO_ALERTA VARCHAR(30) NOT NULL,
    DESCRICAO VARCHAR(500),
    DT_ALERTA TIMESTAMP NOT NULL,
    LIDO BOOLEAN NOT NULL DEFAULT FALSE,
    ID_PET UUID NOT NULL,
    ID_TUTOR UUID NOT NULL,
    CONSTRAINT PK_TB_ALERTA PRIMARY KEY (ID_ALERTA),
    CONSTRAINT FK_ALERTA_PET FOREIGN KEY (ID_PET) REFERENCES TB_PET(ID_PET),
    CONSTRAINT FK_ALERTA_TUTOR FOREIGN KEY (ID_TUTOR) REFERENCES TB_TUTOR(ID_TUTOR)
);
